# Setup
title:               README
tagline:             
description:         '프로젝트를 진행하면서 만나는 <br>기술과 에러 <br>+나의 생각을 기록하는 공간입니다<br><br><a href="https://github.com/TaewoooongHeo01" target="_blank"><img style="width: 35px; height: 35px" src="https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png" alt="GitHub"></a>'
url:                 https://TaewoooongHeo01.github.io
baseurl:             '/TaewoooongHeo01'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Taewoong Heo
  url:               https://github.com/TaewoooongHeo01
  email:             chamjoeun0111@gmail.com

#future date
future: true

#code highlight
markdown: kramdown
kramdown:
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: G-2FDJJ0DP10

google_site_verification: fpHIZwUl25zQL72Z8DsFHC2G97GmToki09OquVoMkyE

